export interface ScoreDetails {
  duration: number;
  positiveKeywords: number;
  negativeKeywords: number;
  negativeNamewords: number;
  authorMatch: number;
  autoGenerated: number;
  bonus: number;
}

export interface TrackMatch<T> {
  totalScore: number;
  scoreDetails: ScoreDetails;
}